// ---------------------------------------------------------------------
// components/ui/Icon.tsx
// Demo-day hardening · Step 7 — standardized icon wrapper (lucide-react).
//
// Single, consistent entry point for every icon in the app:
//   • name       — a Lucide icon name, TYPED against the ICON_REGISTRY
//                  below (typos are compile errors; autocomplete works).
//                  Only lucide-react icons live here — no mixing icon
//                  libraries (design-system rule).
//   • size       — number (px, width = height) OR one of the semantic
//                  presets: "nav" (20, default) · "action" (24) ·
//                  "inline" (16).
//   • className  — passed straight to the underlying <svg>.
//
// Every icon renders with strokeWidth={1.5} (lucide's default is 2) so
// icons stay visually consistent at any size; the stroke scales with the
// icon (relative), which keeps proportions identical from a 16px inline
// chip to a 24px action button.
//
// The registry is an explicit allowlist (named imports → tree-shakeable,
// no runtime string→module lookup, no dynamic import flash). Adding an
// icon = one import + one registry line. It currently covers every icon
// imported anywhere in the app, so gradual migration is drop-in.
// ---------------------------------------------------------------------

import {
  Activity,
  AlarmClock,
  AlertTriangle,
  ArrowDownRight,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  BadgeCheck,
  Battery,
  BatteryFull,
  BatteryLow,
  BatteryMedium,
  Bell,
  BellOff,
  Bot,
  BotMessageSquare,
  Building2,
  Cable,
  CalendarClock,
  Camera,
  Check,
  CheckCircle2,
  CheckSquare,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ClipboardList,
  Clock,
  CloudAlert,
  CloudRain,
  CloudSync,
  Coins,
  Construction,
  Contrast,
  CornerDownLeft,
  Crop,
  Crosshair,
  Database,
  DatabaseZap,
  Download,
  Droplets,
  Eraser,
  ExternalLink,
  Eye,
  EyeOff,
  FileJson,
  FilePlus,
  FileSpreadsheet,
  FileText,
  FileUp,
  Fingerprint,
  Flame,
  Gauge,
  Globe,
  Globe2,
  GripVertical,
  Hand,
  HandHeart,
  HeartPulse,
  Helicopter,
  Hexagon,
  History,
  Home,
  Image as ImageIcon,
  Inbox,
  Keyboard,
  KeyRound,
  Landmark,
  Languages,
  Layers,
  LayoutDashboard,
  Leaf,
  Loader2,
  LocateFixed,
  Lock,
  LogOut,
  Mail,
  Mailbox,
  Map as MapIcon,
  MapPin,
  MapPinPlus,
  MapPinned,
  Maximize,
  Maximize2,
  Megaphone,
  Menu,
  MessageCircle,
  MessageSquare,
  MessageSquareMore,
  MessageSquareText,
  Mic,
  MicOff,
  Minimize,
  Minus,
  Mountain,
  Navigation,
  OctagonAlert,
  Package,
  PackageOpen,
  Paperclip,
  Pause,
  Pencil,
  Phone,
  PhoneCall,
  Play,
  PlugZap,
  Plus,
  Radar,
  Radio,
  RadioTower,
  RefreshCcw,
  RefreshCw,
  RotateCcw,
  RotateCw,
  Route,
  Ruler,
  Satellite,
  Save,
  Scale,
  Scale3D,
  ScrollText,
  Search,
  Send,
  ServerCog,
  Settings,
  Share2,
  Shield,
  ShieldAlert,
  ShieldCheck,
  Ship,
  Siren,
  SlidersHorizontal,
  Sparkles,
  Sun,
  Tent,
  Terminal,
  ThumbsDown,
  ThumbsUp,
  Tornado,
  Trash2,
  TrendingDown,
  TrendingUp,
  TriangleAlert,
  Truck,
  Upload,
  User,
  UserRound,
  UserX,
  Users,
  Volume2,
  Wallet,
  Waves,
  Wifi,
  WifiOff,
  Wrench,
  X,
  XCircle,
  Zap,
  ZoomIn,
} from "lucide-react";
import type { LucideProps } from "lucide-react";

/** Every icon the app may render — `name` is typed as its keys. */
export const ICON_REGISTRY = {
  Activity,
  AlarmClock,
  AlertTriangle,
  ArrowDownRight,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  BadgeCheck,
  Battery,
  BatteryFull,
  BatteryLow,
  BatteryMedium,
  Bell,
  BellOff,
  Bot,
  BotMessageSquare,
  Building2,
  Cable,
  CalendarClock,
  Camera,
  Check,
  CheckCircle2,
  CheckSquare,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ClipboardList,
  Clock,
  CloudAlert,
  CloudRain,
  CloudSync,
  Coins,
  Construction,
  Contrast,
  CornerDownLeft,
  Crop,
  Crosshair,
  Database,
  DatabaseZap,
  Download,
  Droplets,
  Eraser,
  ExternalLink,
  Eye,
  EyeOff,
  FileJson,
  FilePlus,
  FileSpreadsheet,
  FileText,
  FileUp,
  Fingerprint,
  Flame,
  Gauge,
  Globe,
  Globe2,
  GripVertical,
  Hand,
  HandHeart,
  HeartPulse,
  Helicopter,
  Hexagon,
  History,
  Home,
  ImageIcon,
  Inbox,
  Keyboard,
  KeyRound,
  Landmark,
  Languages,
  Layers,
  LayoutDashboard,
  Leaf,
  Loader2,
  LocateFixed,
  Lock,
  LogOut,
  Mail,
  Mailbox,
  MapIcon,
  MapPin,
  MapPinPlus,
  MapPinned,
  Maximize,
  Maximize2,
  Megaphone,
  Menu,
  MessageCircle,
  MessageSquare,
  MessageSquareMore,
  MessageSquareText,
  Mic,
  MicOff,
  Minimize,
  Minus,
  Mountain,
  Navigation,
  OctagonAlert,
  Package,
  PackageOpen,
  Paperclip,
  Pause,
  Pencil,
  Phone,
  PhoneCall,
  Play,
  PlugZap,
  Plus,
  Radar,
  Radio,
  RadioTower,
  RefreshCcw,
  RefreshCw,
  RotateCcw,
  RotateCw,
  Route,
  Ruler,
  Satellite,
  Save,
  Scale,
  Scale3D,
  ScrollText,
  Search,
  Send,
  ServerCog,
  Settings,
  Share2,
  Shield,
  ShieldAlert,
  ShieldCheck,
  Ship,
  Siren,
  SlidersHorizontal,
  Sparkles,
  Sun,
  Tent,
  Terminal,
  ThumbsDown,
  ThumbsUp,
  Tornado,
  Trash2,
  TrendingDown,
  TrendingUp,
  TriangleAlert,
  Truck,
  Upload,
  User,
  UserRound,
  UserX,
  Users,
  Volume2,
  Wallet,
  Waves,
  Wifi,
  WifiOff,
  Wrench,
  X,
  XCircle,
  Zap,
  ZoomIn,
} as const;

/** Type-safe icon name — pick from the registry (autocomplete + typos fail). */
export type IconName = keyof typeof ICON_REGISTRY;

/** Semantic size presets — nav 20px · action 24px · inline 16px. */
export const ICON_SIZES = {
  nav: 20,
  action: 24,
  inline: 16,
} as const;

export type IconSize = number | keyof typeof ICON_SIZES;

/** Uniform stroke width (lucide's default is 2) — set once, used everywhere. */
export const DEFAULT_ICON_STROKE_WIDTH = 1.5;

type IconProps = {
  /** Lucide icon to render (typed against the registry). */
  name: IconName;
  /** px size — number, or "nav" (20, default) · "action" (24) · "inline" (16). */
  size?: IconSize;
  className?: string;
} & Omit<LucideProps, "name" | "size">;

export function Icon({ name, size = "nav", className, ...rest }: IconProps) {
  const IconComponent = ICON_REGISTRY[name];
  const px = typeof size === "number" ? size : ICON_SIZES[size];

  // strokeWidth before {...rest} so an explicit override still wins.
  return (
    <IconComponent
      size={px}
      strokeWidth={DEFAULT_ICON_STROKE_WIDTH}
      className={className}
      {...rest}
    />
  );
}

export default Icon;
