// ---------------------------------------------------------------------
// lib/help-content.ts — Help Center single source of truth.
//
// Every article in /help is defined here. The `image` field points at a
// screenshot generated by `npm run help:shots`
// (scripts/capture-help-shots.mjs → public/help/shots/<id>.webp).
// If a screenshot file doesn't exist yet, <HelpImage> renders a styled
// placeholder frame instead — the site works before shots are captured.
//
// Search matches against title + keywords + summary + step text, so
// phrasing like "how do I report someone missing" finds the right topic.
// ---------------------------------------------------------------------

export type HelpCategory = "emergencies" | "citizen" | "gov" | "account";

export type HelpStep = {
  title: string;
  text: string;
};

export type HelpTopic = {
  id: string;
  title: string;
  category: HelpCategory;
  /** Extra search terms beyond the title. */
  keywords: string[];
  /** One-line answer shown on cards and search results. */
  summary: string;
  steps: HelpStep[];
  /** Screenshot path under /public (no leading slash duplication). */
  image: string;
  related: string[];
};

export const HELP_CATEGORIES: Array<{
  key: HelpCategory;
  label: string;
  blurb: string;
}> = [
  {
    key: "emergencies",
    label: "Emergencies",
    blurb: "SOS, alerts and staying informed during an event",
  },
  {
    key: "citizen",
    label: "Citizen App",
    blurb: "Everyday safety tools for you and your family",
  },
  {
    key: "gov",
    label: "Gov Portal",
    blurb: "Command center, planning and dispatch for officials",
  },
  {
    key: "account",
    label: "Account & Access",
    blurb: "Signing in, requesting access and approvals",
  },
];

export const HELP_TOPICS: HelpTopic[] = [
  // ---------------------------------------------------------- emergencies
  {
    id: "send-sos",
    title: "Sending an SOS emergency request",
    category: "emergencies",
    keywords: [
      "sos", "emergency", "help me", "panic", "rescue", "911", "112",
      "distress", "urgent help", "trapped",
    ],
    summary:
      "Raise an SOS with your live location so the nearest response team is dispatched to you.",
    steps: [
      {
        title: "Open the SOS page",
        text: "Tap the red SOS button on the bottom bar (or visit /sos). No account needed — SOS works for guests too.",
      },
      {
        title: "Allow location access",
        text: "When your browser asks for your location, tap Allow. Your coordinates are attached so responders can find you even if you can't speak.",
      },
      {
        title: "Describe your situation",
        text: "Add a short note (e.g. “water entering house, 4 people”). This is optional but helps triage your request faster.",
      },
      {
        title: "Press SEND SOS",
        text: "Your request is queued with a reference number. Keep your phone reachable — responders will call you back on it.",
      },
      {
        title: "If you can't use the app",
        text: "Call the disaster helpline 1070 directly — the number is shown on every screen in an emergency.",
      },
    ],
    image: "/help/shots/send-sos.webp",
    related: ["citizen-alerts", "citizen-map", "report-issue"],
  },
  {
    id: "citizen-alerts",
    title: "Understanding severity levels & alert colors",
    category: "emergencies",
    keywords: [
      "alert", "warning", "severity", "safe", "watch", "prepare", "evacuate",
      "notification colors", "what does critical mean", "orange red blue",
    ],
    summary:
      "What SAFE / WATCH / PREPARE / EVACUATE mean, and how alerts reach you.",
    steps: [
      {
        title: "Know the four levels",
        text: "SAFE (blue) — no action needed. WATCH (sky) — conditions could worsen; stay tuned. PREPARE (amber) — pack essentials, charge phones. EVACUATE (red) — move to the nearest shelter immediately.",
      },
      {
        title: "Alerts appear three ways",
        text: "In-app banner on every page, push/browser notification if enabled, and SMS for citizens registered with a phone number.",
      },
      {
        title: "Critical alerts bypass Quiet Hours",
        text: "EVACUATE-level warnings always ring through, even when notifications are muted — your safety overrides settings.",
      },
      {
        title: "Check your district's status anytime",
        text: "The colored banner at the top of the dashboard shows your current level. Open Alerts for the full history with timestamps.",
      },
    ],
    image: "/help/shots/citizen-alerts.webp",
    related: ["send-sos", "citizen-dashboard"],
  },

  // -------------------------------------------------------------- citizen
  {
    id: "landing",
    title: "Touring the platform landing page",
    category: "citizen",
    keywords: [
      "home", "landing", "start here", "what is safesphere", "overview",
      "features", "demo", "download",
    ],
    summary:
      "Start here — what SafeSphere does, who it's for, and where everything lives.",
    steps: [
      {
        title: "Two doors, one platform",
        text: "“I'm a Resident” opens the citizen app (safety status, SOS, family tracking). “Government Login” opens the command center for officials.",
      },
      {
        title: "Scroll the feature tour",
        text: "Sections walk through prediction, communication, and the command center with live screenshots of both portals.",
      },
      {
        title: "Try without installing",
        text: "Everything runs in the browser. The Download page offers an installable PWA for offline-capable access on phones.",
      },
      {
        title: "Stuck? Open Help anytime",
        text: "The Help link in the navbar brings you here — searchable answers with real screenshots of every screen.",
      },
    ],
    image: "/help/shots/landing.webp",
    related: ["citizen-dashboard", "gov-login"],
  },
  {
    id: "citizen-dashboard",
    title: "Reading your safety dashboard",
    category: "citizen",
    keywords: [
      "dashboard", "safety status", "home screen", "my area safe",
      "family strip", "shelters near me", "forecast", "battery saver",
    ],
    summary:
      "Your one-screen view: current risk level, family status, nearby shelters and the 3-day forecast.",
    steps: [
      {
        title: "Safety banner first",
        text: "The top card shows your geo-detected district's level (SAFE/WATCH/PREPARE/EVACUATE) plus a contextual action for right now.",
      },
      {
        title: "Family strip",
        text: "Avatar dots show each family member's status: green = marked safe. Tap anyone to send a check-in nudge via WhatsApp/SMS.",
      },
      {
        title: "Nearest shelters",
        text: "Three closest shelters with walking time and occupancy. Tap one for turn-by-turn directions.",
      },
      {
        title: "Low bandwidth mode",
        text: "On weak networks the app automatically drops heavy panels (AI chat, map) and keeps life-safety info first. Battery Saver does the same manually.",
      },
    ],
    image: "/help/shots/citizen-dashboard.webp",
    related: ["citizen-map", "citizen-alerts", "send-sos"],
  },
  {
    id: "citizen-map",
    title: "Using the citizen map (flood zones & shelters)",
    category: "citizen",
    keywords: [
      "map", "flood zone", "shelter map", "am i in a flood zone",
      "evacuation route", "directions", "nearby",
    ],
    summary:
      "See flood polygons, shelter locations and safe routes relative to your home.",
    steps: [
      {
        title: "Red = flooded",
        text: "Flood-zone polygons show model-predicted inundation. If your home sits inside one, follow the PREPARE/EVACUATE guidance.",
      },
      {
        title: "Green pins = shelters",
        text: "Tap any shelter pin for capacity status, facilities (food/medical) and a directions link that opens your maps app.",
      },
      {
        title: "Routes avoid danger",
        text: "Evacuation routes are drawn to steer around active flood polygons and road closures reported by field teams.",
      },
      {
        title: "Offline fallback",
        text: "Recently viewed map data is cached. With no signal you still see the last-known zones and shelter list.",
      },
    ],
    image: "/help/shots/citizen-map.webp",
    related: ["citizen-dashboard", "live-map"],
  },
  {
    id: "report-issue",
    title: "Reporting a problem (flooding, damage, blocked roads)",
    category: "citizen",
    keywords: [
      "report", "crowdsource", "flooding report", "damage photo",
      "blocked road", "submit issue", "see something say something",
    ],
    summary:
      "Send a geo-tagged photo report straight into the district control room queue.",
    steps: [
      {
        title: "Open Report from the dashboard",
        text: "Choose what you saw: flooding, infrastructure damage, blocked road, or other.",
      },
      {
        title: "Attach a photo",
        text: "Photos are watermarked with time + coordinates on upload — this is what makes your report verifiable.",
      },
      {
        title: "Pin the location",
        text: "Drag the pin to the exact spot if GPS isn't precise (useful inside buildings).",
      },
      {
        title: "Officials verify it",
        text: "Reports land in the gov Crowdsourced Reports widget as “unverified”. Once an official taps Verify, it feeds the live map for everyone.",
      },
    ],
    image: "/help/shots/report-issue.webp",
    related: ["citizen-map", "command-center-dashboard"],
  },
  {
    id: "nova-ai-chat",
    title: "Asking Nova, the AI safety assistant",
    category: "citizen",
    keywords: [
      "ai", "chatbot", "nova", "ask question", "assistant",
      "nearest hospital", "what should i do", "chat",
    ],
    summary:
      "Ask natural-language questions — Nova answers with your district's live data and can dial helplines for you.",
    steps: [
      {
        title: "Find the chat",
        text: "Tap the AI prompt card on the dashboard (or go to /public/ai). Suggested prompts cover the most common needs.",
      },
      {
        title: "Ask in plain language",
        text: "“Is my area safe tonight?” or “nearest hospital with oxygen” — Nova checks shelters, alerts and predictions before answering.",
      },
      {
        title: "Act on response cards",
        text: "Answers include tappable action cards: call 1070, open shelter directions, or start an SOS — not just text.",
      },
      {
        title: "Works in low bandwidth",
        text: "On 2G the assistant switches to lightweight mode: shorter replies, no heavy cards, same life-safety accuracy.",
      },
    ],
    image: "/help/shots/nova-ai-chat.webp",
    related: ["citizen-dashboard", "send-sos"],
  },

  // ------------------------------------------------------------------ gov
  {
    id: "command-center-dashboard",
    title: "Running the District Command Overview",
    category: "gov",
    keywords: [
      "dashboard", "command center", "district overview", "kpi",
      "situation awareness", "ops", "critical events", "at risk",
    ],
    summary:
      "The mission-control home: live KPIs, operations map, incoming alerts and AI suggestions in one grid.",
    steps: [
      {
        title: "Read the KPI row first",
        text: "Current risk, people at risk, shelter load and resource units update live — counters animate as new data syncs.",
      },
      {
        title: "Live Operations Map",
        text: "Toggle Flood Zones, Shelters, Responders and Routes layers. Click any polygon or pin for details.",
      },
      {
        title: "Incoming Alerts panel",
        text: "Newest system alerts stream in with channel badges. Use Alerts/Timeline tabs to switch between live feed and chronology.",
      },
      {
        title: "Verify crowdsourced reports",
        text: "Citizen reports arrive flagged unverified. Verify pushes them to the public map; Reject removes them. Every decision is audit-logged.",
      },
      {
        title: "View as Public",
        text: "The toggle top-right previews exactly what citizens see — essential before broadcasting anything.",
      },
    ],
    image: "/help/shots/command-center-dashboard.webp",
    related: ["alerts-console", "ai-planner", "access-requests"],
  },
  {
    id: "operations-overview",
    title: "72-hour forecast & operational metrics",
    category: "gov",
    keywords: [
      "forecast", "72 hour", "prediction", "river level", "rainfall chart",
      "metrics", "trend", "history",
    ],
    summary:
      "Model forecasts for the next 72 hours plus historical trend charts per district.",
    steps: [
      {
        title: "Forecast chart",
        text: "The area chart projects river stage/rainfall for the next 72h. Hover any point for exact values and confidence.",
      },
      {
        title: "Risk bands",
        text: "Horizontal bands mark Watch/Warning thresholds from NDMA guidelines — when the line crosses a band, alerts auto-draft.",
      },
      {
        title: "History selector",
        text: "Switch between 2/7/14-day history to compare today against previous events in the same district.",
      },
    ],
    image: "/help/shots/operations-overview.webp",
    related: ["command-center-dashboard", "ai-planner"],
  },
  {
    id: "live-map",
    title: "Working the live operations map",
    category: "gov",
    keywords: [
      "map", "layers", "flood polygon", "responders", "measure",
      "draw zone", "satellite", "terrain", "export",
    ],
    summary:
      "Full tactical canvas: layer toggles, measurement tools, drawing and export.",
    steps: [
      {
        title: "Toggle layers",
        text: "Layer control (left) switches Flood Zones, Shelters, Responders, Routes, Satellite basemap and 3D terrain.",
      },
      {
        title: "Measure distances",
        text: "The ruler tool measures polyline distance/area — useful for estimating evacuation corridor lengths.",
      },
      {
        title: "Draw & publish zones",
        text: "Draw a polygon, name it, and publish to push a new warning zone to citizen devices in that area.",
      },
      {
        title: "Export for briefings",
        text: "Export Map downloads a PNG snapshot (current layers + timestamp) for slide decks and SitReps.",
      },
    ],
    image: "/help/shots/live-map.webp",
    related: ["command-center-dashboard", "operations-overview"],
  },
  {
    id: "ai-planner",
    title: "Generating AI evacuation plans",
    category: "gov",
    keywords: [
      "ai planner", "plan", "evacuation plan", "agent", "orchestration",
      "approve plan", "what-if", "simulation", "rag", "ndma",
    ],
    summary:
      "Multi-agent AI drafts a 48-hour evacuation plan grounded in your SOPs — you approve before anything ships.",
    steps: [
      {
        title: "Describe the scenario",
        text: "Left pane: state the situation (“Ganga crossing danger mark at Kankarbagh, 12k affected”). Pick a persona tone if needed.",
      },
      {
        title: "Watch the agents work",
        text: "The orchestration flow shows each agent (data fetcher, risk analyst, route planner) with live status as they ground the plan in real data.",
      },
      {
        title: "Review the Field Operation Order",
        text: "Output renders as a structured order: priorities, routes, shelter assignments, resource calls — each backed by cited SOP sources (RAG panel).",
      },
      {
        title: "Approve, edit or simulate",
        text: "Approve dispatches it to teams. What-If re-runs with tweaks (“bridge closed”). Nothing reaches citizens until a human approves.",
      },
    ],
    image: "/help/shots/ai-planner.webp",
    related: ["command-center-dashboard", "alerts-console"],
  },
  {
    id: "alerts-console",
    title: "Composing & broadcasting alerts",
    category: "gov",
    keywords: [
      "alert composer", "broadcast", "sms blast", "send notification",
      "channels", "template", "translate", "fm radio", "a/b test",
    ],
    summary:
      "Draft once, deliver everywhere: in-app, SMS, WhatsApp, voice call, FM radio ticker and email.",
    steps: [
      {
        title: "Pick severity & type",
        text: "Severity sets color and urgency handling; type (flood, cyclone…) selects the pre-approved template skeleton.",
      },
      {
        title: "Target precisely",
        text: "Choose entire district, selected villages, or draw a custom polygon on the target map.",
      },
      {
        title: "Use templates & translations",
        text: "Template Library holds approved wording. Translation preview drafts Hindi/Bengali/Tamil variants you can edit before sending.",
      },
      {
        title: "Send now or schedule",
        text: "Immediate fires on all selected channels. Scheduled stages it (critical alerts still bypass quiet hours). Delivery Tracking shows per-channel progress after send.",
      },
    ],
    image: "/help/shots/alerts-console.webp",
    related: ["command-center-dashboard", "request-access"],
  },
  {
    id: "shelters",
    title: "Managing shelter capacity",
    category: "gov",
    keywords: [
      "shelter", "capacity", "occupancy", "full", "beds",
      "facilities", "shelter update",
    ],
    summary:
      "Track occupancy across shelters and push updates citizens see instantly.",
    steps: [
      {
        title: "Scan the table",
        text: "Each row shows capacity vs current occupancy with a color badge: green (space), amber (filling), red (full).",
      },
      {
        title: "Update counts",
        text: "Edit occupancy inline as field teams report numbers. Changes revalidate the public cache within seconds.",
      },
      {
        title: "Facilities matter",
        text: "Keep food/medical flags accurate — citizens filter shelters by these when choosing where to go.",
      },
    ],
    image: "/help/shots/shelters.webp",
    related: ["citizen-map", "command-center-dashboard"],
  },

  // -------------------------------------------------------------- account
  {
    id: "gov-login",
    title: "Signing in to the government portal",
    category: "account",
    keywords: [
      "login", "sign in", "gov login", "official", "password",
      "can't log in", "pending approval", "credentials",
    ],
    summary:
      "Official access is approval-gated — only emails cleared by a super admin can sign in.",
    steps: [
      {
        title: "Go to Login → Government tab",
        text: "Enter your official email (preferably a .gov.in address) and password.",
      },
      {
        title: "First time? Request access",
        text: "Use the “Request access” link. Submit your name, organisation and Employee/Volunteer ID — it's emailed to the SafeSphere team for verification.",
      },
      {
        title: "Wait for approval",
        text: "While pending you'll see “Access request is pending admin approval”. An admin approves you at /access-requests, then you're in.",
      },
      {
        title: "Pick your role for the demo",
        text: "During demos, the role selector (District Admin / Super Admin) chooses which workspace loads after sign-in.",
      },
    ],
    image: "/help/shots/gov-login.webp",
    related: ["request-access", "access-requests"],
  },
  {
    id: "request-access",
    title: "Requesting official access",
    category: "account",
    keywords: [
      "request access", "signup", "register official", "employee id",
      "verification document", "ndrf sdrf", "new account",
    ],
    summary:
      "Officials register with an ID document; the SafeSphere team verifies and approves.",
    steps: [
      {
        title: "Open Request Access",
        text: "From the gov login screen, tap “Request access →”.",
      },
      {
        title: "Fill your details",
        text: "Name, official email, organisation (NDRF / SDRF / District Admin) and a strong password.",
      },
      {
        title: "Attach your ID",
        text: "Upload an Employee/Volunteer ID (JPG/PNG/PDF up to 5 MB). It travels with your application email for identity checks.",
      },
      {
        title: "Submit & watch your inbox",
        text: "You'll see “Account Pending Admin Approval”. Approval unlocks sign-in with the same email; no separate activation mail needed.",
      },
    ],
    image: "/help/shots/request-access.webp",
    related: ["gov-login", "access-requests"],
  },
  {
    id: "access-requests",
    title: "Approving access requests (admins)",
    category: "account",
    keywords: [
      "approve user", "admin approval", "access requests portal",
      "grant role", "reject request", "who can log in",
    ],
    summary:
      "Super admins review submitted requests and grant portal access with the right role.",
    steps: [
      {
        title: "Open Access Requests",
        text: "Sidebar → ADMIN → Access Requests. Pending submissions show requester details, organisation and requested role.",
      },
      {
        title: "Verify the person",
        text: "Cross-check the emailed ID document against the requester details before approving.",
      },
      {
        title: "Grant the right role",
        text: "Pick Field Responder or District Admin, then Approve. That email can sign in immediately; Rejected stays locked out.",
      },
      {
        title: "Whitelist shortcut",
        text: "Trusted always-on accounts (e.g. the state EOC) can be pre-cleared via the GOV_ACCESS_WHITELIST env var — no request needed.",
      },
    ],
    image: "/help/shots/access-requests.webp",
    related: ["gov-login", "request-access"],
  },
];

/** Look up one topic, undefined when the slug doesn't exist. */
export function getHelpTopic(id: string): HelpTopic | undefined {
  return HELP_TOPICS.find((t) => t.id === id);
}

/** All topics in a category, config order. */
export function topicsByCategory(category: HelpCategory): HelpTopic[] {
  return HELP_TOPICS.filter((t) => t.category === category);
}

/** Client-side search across title, keywords, summary and step text. */
export function searchHelpTopics(query: string): HelpTopic[] {
  const q = query.trim().toLowerCase();
  if (!q) return HELP_TOPICS;
  const terms = q.split(/\s+/);
  return HELP_TOPICS.map((topic) => {
    const haystack = [
      topic.title,
      topic.summary,
      ...topic.keywords,
      ...topic.steps.flatMap((s) => [s.title, s.text]),
    ]
      .join(" ")
      .toLowerCase();
    const score = terms.reduce(
      (acc, term) => acc + (haystack.includes(term) ? 1 : 0),
      0,
    );
    return { topic, score };
  })
    .filter(({ score }) => score > 0)
    .sort((a, b) => b.score - a.score)
    .map(({ topic }) => topic);
}
