// ---------------------------------------------------------------------
// lib/fm/mock-stations.ts — Phase 26 · FM Radio Emergency Broadcasting
//
// Demo fallback station list, used by the FM API routes when the
// fm_stations table is unreachable (DB not migrated / offline) so the
// admin UI and the "Test Coverage" tool keep working before the
// migrations are pushed — same pattern as SHELTER_MOCK in DisasterMap.
//
// Seeded with real broadcasters across the spec's target cities:
// metros (Delhi, Mumbai, Kolkata), tier-2 (Patna, Lucknow, Bhubaneswar)
// and flood-prone tier-3 (Muzaffarpur), with AIR stations included
// (mandatory EWS broadcast obligation). DB rows always win when present;
// this list is only the fallback.
// ---------------------------------------------------------------------

import type { FmStationDTO } from "./serialize";

// Module-load timestamp — mock rows are never written, but a real-looking
// value keeps the admin table's created/updated columns sensible.
const mockTimestamp = new Date().toISOString();

export const MOCK_FM_STATIONS: FmStationDTO[] = [
  {
    id: "mock-fm-air-patna",
    name: "AIR Patna Vividh Bharati",
    frequency: "101.7 MHz",
    city: "Patna",
    state: "Bihar",
    callSign: "FM-PR-01",
    coverageRadiusKm: 80,
    lat: 25.598,
    lng: 85.13,
    operator: "All India Radio (Prasar Bharati)",
    type: "air",
    emergencyApiEndpoint: null,
    emergencyContactPhone: "+91-612-2221234",
    rdsEnabled: true,
    rdsApiEndpoint: null,
    isActive: true,
    createdAt: mockTimestamp,
    updatedAt: mockTimestamp,
  },
  {
    id: "mock-fm-mirchi-patna",
    name: "Radio Mirchi 98.3",
    frequency: "98.3 MHz",
    city: "Patna",
    state: "Bihar",
    callSign: "FM-PR-02",
    coverageRadiusKm: 50,
    lat: 25.5941,
    lng: 85.1376,
    operator: "Entertainment Network India Ltd",
    type: "private",
    emergencyApiEndpoint: null,
    emergencyContactPhone: "+91-612-2209830",
    rdsEnabled: true,
    rdsApiEndpoint: null,
    isActive: true,
    createdAt: mockTimestamp,
    updatedAt: mockTimestamp,
  },
  {
    id: "mock-fm-redfm-patna",
    name: "Red FM 93.5",
    frequency: "93.5 MHz",
    city: "Patna",
    state: "Bihar",
    callSign: "FM-PR-03",
    coverageRadiusKm: 50,
    lat: 25.61,
    lng: 85.14,
    operator: "Sun Group",
    type: "private",
    emergencyApiEndpoint: null,
    emergencyContactPhone: "+91-612-2293500",
    rdsEnabled: true,
    rdsApiEndpoint: null,
    isActive: true,
    createdAt: mockTimestamp,
    updatedAt: mockTimestamp,
  },
  {
    id: "mock-fm-bigfm-patna",
    name: "BIG FM 92.7",
    frequency: "92.7 MHz",
    city: "Patna",
    state: "Bihar",
    callSign: "FM-PR-04",
    coverageRadiusKm: 45,
    lat: 25.6,
    lng: 85.12,
    operator: "Reliance Broadcast Network",
    type: "private",
    emergencyApiEndpoint: null,
    emergencyContactPhone: "+91-612-2292700",
    rdsEnabled: false,
    rdsApiEndpoint: null,
    isActive: true,
    createdAt: mockTimestamp,
    updatedAt: mockTimestamp,
  },
  {
    id: "mock-fm-mantra-muzaffarpur",
    name: "Radio Mantra 90.4",
    frequency: "90.4 MHz",
    city: "Muzaffarpur",
    state: "Bihar",
    callSign: "FM-MZ-01",
    coverageRadiusKm: 30,
    lat: 26.1225,
    lng: 85.3908,
    operator: "Muzaffarpur Community Radio",
    type: "community",
    emergencyApiEndpoint: null,
    emergencyContactPhone: "+91-621-2229040",
    rdsEnabled: false,
    rdsApiEndpoint: null,
    isActive: true,
    createdAt: mockTimestamp,
    updatedAt: mockTimestamp,
  },
  {
    id: "mock-fm-air-rainbow-delhi",
    name: "AIR FM Rainbow 102.6",
    frequency: "102.6 MHz",
    city: "Delhi",
    state: "Delhi",
    callSign: "FM-DL-01",
    coverageRadiusKm: 60,
    lat: 28.6139,
    lng: 77.209,
    operator: "All India Radio (Prasar Bharati)",
    type: "air",
    emergencyApiEndpoint: null,
    emergencyContactPhone: "+91-11-23310126",
    rdsEnabled: true,
    rdsApiEndpoint: null,
    isActive: true,
    createdAt: mockTimestamp,
    updatedAt: mockTimestamp,
  },
  {
    id: "mock-fm-air-gold-delhi",
    name: "AIR FM Gold 106.4",
    frequency: "106.4 MHz",
    city: "Delhi",
    state: "Delhi",
    callSign: "FM-DL-02",
    coverageRadiusKm: 60,
    lat: 28.61,
    lng: 77.2,
    operator: "All India Radio (Prasar Bharati)",
    type: "air",
    emergencyApiEndpoint: null,
    emergencyContactPhone: "+91-11-23310126",
    rdsEnabled: true,
    rdsApiEndpoint: null,
    isActive: true,
    createdAt: mockTimestamp,
    updatedAt: mockTimestamp,
  },
  {
    id: "mock-fm-city-mumbai",
    name: "Radio City 91.1",
    frequency: "91.1 MHz",
    city: "Mumbai",
    state: "Maharashtra",
    callSign: "FM-MH-01",
    coverageRadiusKm: 55,
    lat: 19.076,
    lng: 72.8777,
    operator: "Music Broadcast Ltd",
    type: "private",
    emergencyApiEndpoint: null,
    emergencyContactPhone: "+91-22-66919100",
    rdsEnabled: true,
    rdsApiEndpoint: null,
    isActive: true,
    createdAt: mockTimestamp,
    updatedAt: mockTimestamp,
  },
  {
    id: "mock-fm-mirchi-lucknow",
    name: "Radio Mirchi 98.3",
    frequency: "98.3 MHz",
    city: "Lucknow",
    state: "Uttar Pradesh",
    callSign: "FM-UP-01",
    coverageRadiusKm: 50,
    lat: 26.8467,
    lng: 80.9462,
    operator: "Entertainment Network India Ltd",
    type: "private",
    emergencyApiEndpoint: null,
    emergencyContactPhone: "+91-522-2209830",
    rdsEnabled: true,
    rdsApiEndpoint: null,
    isActive: true,
    createdAt: mockTimestamp,
    updatedAt: mockTimestamp,
  },
  {
    id: "mock-fm-air-rainbow-kolkata",
    name: "AIR FM Rainbow 107.1",
    frequency: "107.1 MHz",
    city: "Kolkata",
    state: "West Bengal",
    callSign: "FM-WB-01",
    coverageRadiusKm: 60,
    lat: 22.5726,
    lng: 88.3639,
    operator: "All India Radio (Prasar Bharati)",
    type: "air",
    emergencyApiEndpoint: null,
    emergencyContactPhone: "+91-33-22261200",
    rdsEnabled: true,
    rdsApiEndpoint: null,
    isActive: true,
    createdAt: mockTimestamp,
    updatedAt: mockTimestamp,
  },
  {
    id: "mock-fm-choklate-bhubaneswar",
    name: "Radio Choklate 104.8",
    frequency: "104.8 MHz",
    city: "Bhubaneswar",
    state: "Odisha",
    callSign: "FM-OD-01",
    coverageRadiusKm: 45,
    lat: 20.2961,
    lng: 85.8245,
    operator: "Manadi O Media Pvt Ltd",
    type: "private",
    emergencyApiEndpoint: null,
    emergencyContactPhone: "+91-674-2301048",
    rdsEnabled: false,
    rdsApiEndpoint: null,
    isActive: true,
    createdAt: mockTimestamp,
    updatedAt: mockTimestamp,
  },
];
