export type EvacuationPlanLike = {
  id: string;
  villageName: string;
  assignedShelterId: string;
  estimatedEvacuees: number;
  status: string;
  routeGeoJson: string;
  shelterName?: string;
  createdAt?: string;
};

/**
 * Save an evacuation plan generated by the Mass Evacuation Planner.
 * Never throws — returns null on failure so the UI is unaffected.
 */
export async function saveEvacuationPlan(input: {
  villageName: string;
  assignedShelterId: string;
  estimatedEvacuees?: number;
  routeGeoJson?: string;
  status?: string;
}): Promise<EvacuationPlanLike | null> {
  try {
    const response = await fetch("/api/evacuation-plans", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(input),
    });
    if (!response.ok) return null;
    const data = (await response.json()) as { plan?: EvacuationPlanLike };
    return data.plan ?? null;
  } catch {
    return null;
  }
}

/** Load recent evacuation plans for the tracker UI. */
export async function fetchEvacuationPlans(): Promise<EvacuationPlanLike[]> {
  try {
    const response = await fetch("/api/evacuation-plans", { cache: "no-store" });
    if (!response.ok) return [];
    const data = (await response.json()) as { plans?: EvacuationPlanLike[] };
    return data.plans ?? [];
  } catch {
    return [];
  }
}
